runtime: python27
api_version: 1
threadsafe: true

handlers:   
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /set_webhook
  login: admin
  script: main.app

- url: /login.html
  static_files: www/login.html
  upload: www/login.html
  secure: always

- url: /script.js
  static_files: www/script.js
  upload: www/script.js
  secure: always

- url: /style.css
  static_files: www/style.css
  upload: www/style.css
  secure: always

- url: /sjCxccZ.jpg
  static_files: www/sjCxccZ.jpg
  upload: www/sjCxccZ.jpg
  secure: always

- url: /.+
  script: main.app
  
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest
- name: PIL
  version: latest
- name: endpoints
  version: latest