#!/bin/sh

"[[GoogleCloudSDKInstallation]]/Google/Cloud SDK/google-cloud-sdk/bin/gcloud.cmd" app deploy app.yaml --project [[GoogleAppEngineProjectName]]
"[[PythonInstallation]]/python.exe" "[[GooglePythonAppEngineSDKInstallation]]/Google/google_appengine/appcfg.py" update_cron "./" --application [[GoogleAppEngineProjectName]]